/*
 * Copyright 2024 The KubeVirt Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubevirt.io/dra-pci-driver/api/kubevirt.io/resource/pci/v1alpha1"
)

// FakePciClaimParameters implements PciClaimParametersInterface
type FakePciClaimParameters struct {
	Fake *FakePciV1alpha1
	ns   string
}

var pciclaimparametersResource = v1alpha1.SchemeGroupVersion.WithResource("pciclaimparameters")

var pciclaimparametersKind = v1alpha1.SchemeGroupVersion.WithKind("PciClaimParameters")

// Get takes name of the pciClaimParameters, and returns the corresponding pciClaimParameters object, and an error if there is any.
func (c *FakePciClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PciClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pciclaimparametersResource, c.ns, name), &v1alpha1.PciClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PciClaimParameters), err
}

// List takes label and field selectors, and returns the list of PciClaimParameters that match those selectors.
func (c *FakePciClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PciClaimParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pciclaimparametersResource, pciclaimparametersKind, c.ns, opts), &v1alpha1.PciClaimParametersList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PciClaimParametersList{ListMeta: obj.(*v1alpha1.PciClaimParametersList).ListMeta}
	for _, item := range obj.(*v1alpha1.PciClaimParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pciClaimParameters.
func (c *FakePciClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pciclaimparametersResource, c.ns, opts))

}

// Create takes the representation of a pciClaimParameters and creates it.  Returns the server's representation of the pciClaimParameters, and an error, if there is any.
func (c *FakePciClaimParameters) Create(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.CreateOptions) (result *v1alpha1.PciClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pciclaimparametersResource, c.ns, pciClaimParameters), &v1alpha1.PciClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PciClaimParameters), err
}

// Update takes the representation of a pciClaimParameters and updates it. Returns the server's representation of the pciClaimParameters, and an error, if there is any.
func (c *FakePciClaimParameters) Update(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.PciClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pciclaimparametersResource, c.ns, pciClaimParameters), &v1alpha1.PciClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PciClaimParameters), err
}

// Delete takes name of the pciClaimParameters and deletes it. Returns an error if one occurs.
func (c *FakePciClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(pciclaimparametersResource, c.ns, name, opts), &v1alpha1.PciClaimParameters{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePciClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pciclaimparametersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PciClaimParametersList{})
	return err
}

// Patch applies the patch and returns the patched pciClaimParameters.
func (c *FakePciClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PciClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pciclaimparametersResource, c.ns, name, pt, data, subresources...), &v1alpha1.PciClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PciClaimParameters), err
}
