/*
 * Copyright 2024 The KubeVirt Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubevirt.io/dra-pci-driver/api/kubevirt.io/resource/pci/v1alpha1"
	scheme "kubevirt.io/dra-pci-driver/pkg/kubevirt.io/resource/clientset/versioned/scheme"
)

// PciClaimParametersGetter has a method to return a PciClaimParametersInterface.
// A group's client should implement this interface.
type PciClaimParametersGetter interface {
	PciClaimParameters(namespace string) PciClaimParametersInterface
}

// PciClaimParametersInterface has methods to work with PciClaimParameters resources.
type PciClaimParametersInterface interface {
	Create(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.CreateOptions) (*v1alpha1.PciClaimParameters, error)
	Update(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.UpdateOptions) (*v1alpha1.PciClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PciClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PciClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PciClaimParameters, err error)
	PciClaimParametersExpansion
}

// pciClaimParameters implements PciClaimParametersInterface
type pciClaimParameters struct {
	client rest.Interface
	ns     string
}

// newPciClaimParameters returns a PciClaimParameters
func newPciClaimParameters(c *PciV1alpha1Client, namespace string) *pciClaimParameters {
	return &pciClaimParameters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pciClaimParameters, and returns the corresponding pciClaimParameters object, and an error if there is any.
func (c *pciClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PciClaimParameters, err error) {
	result = &v1alpha1.PciClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PciClaimParameters that match those selectors.
func (c *pciClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PciClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PciClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pciClaimParameters.
func (c *pciClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pciClaimParameters and creates it.  Returns the server's representation of the pciClaimParameters, and an error, if there is any.
func (c *pciClaimParameters) Create(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.CreateOptions) (result *v1alpha1.PciClaimParameters, err error) {
	result = &v1alpha1.PciClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pciClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pciClaimParameters and updates it. Returns the server's representation of the pciClaimParameters, and an error, if there is any.
func (c *pciClaimParameters) Update(ctx context.Context, pciClaimParameters *v1alpha1.PciClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.PciClaimParameters, err error) {
	result = &v1alpha1.PciClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		Name(pciClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pciClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pciClaimParameters and deletes it. Returns an error if one occurs.
func (c *pciClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pciClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pciclaimparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pciClaimParameters.
func (c *pciClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PciClaimParameters, err error) {
	result = &v1alpha1.PciClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pciclaimparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
