---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dra-pci-driver-role
  namespace: dra-pci-driver
rules:
  - apiGroups:
      - ""
      - resource.k8s.io
      - pci.resource.kubevirt.io
      - nas.pci.resource.kubevirt.io
    resources: ["*"]
    verbs: ["*"]
