---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dra-pci-driver-controller
  namespace: dra-pci-driver
  labels:
    app.kubernetes.io/name: dra-pci-driver
    app.kubernetes.io/instance: dra-pci-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dra-pci-driver
      app.kubernetes.io/instance: dra-pci-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dra-pci-driver
        app.kubernetes.io/instance: dra-pci-driver
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: dra-pci-driver-service-account
      containers:
        - name: controller
          image: registry:5000/registry.example.com/dra-pci-driver:v0.1.0
          imagePullPolicy: Always
          command: ["virt-dra-controller"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
