apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-pci-driver-service-account
  namespace: dra-pci-driver
  labels:
    app.kubernetes.io/name: dra-pci-driver
    app.kubernetes.io/instance: dra-pci-driver
