---
apiVersion: v1
kind: Namespace
metadata:
  name: pci-nvme-test1
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: pci.resource.kubevirt.io/v1alpha1
kind: PciClaimParameters
metadata:
  name: nvme-params
  namespace: pci-nvme-test1
spec:
  deviceName: "devices.kubevirt.io/nvme"
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
 namespace: pci-nvme-test1
 name: test-pci-claim-template
spec:
 spec:
   resourceClassName: pci.kubevirt.io
   parametersRef:
     apiGroup: pci.resource.kubevirt.io
     kind: PciClaimParameters
     name: nvme-params
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  namespace: pci-nvme-test1
  name: test-pci-claim
spec:
  resourceClassName: pci.kubevirt.io
  parametersRef:
    apiGroup: pci.resource.kubevirt.io
    kind: PciClaimParameters
    name: nvme-params
---
apiVersion: v1
kind: Pod
metadata:
  namespace: pci-nvme-test1
  name: pod0
  labels:
    app: pod
spec:
  containers:
    - name: ctr0
      image: registry:5000/docker.io/library/ubuntu:22.04
      command: ["bash", "-c"]
      args: ["export; sleep 9999"]
      resources:
        claims:
          - name: pci1
          - name: pci2
  resourceClaims:
    - name: pci1
      source:
        resourceClaimName: test-pci-claim
    - name: pci2
      source:
        resourceClaimTemplateName: test-pci-claim-template


